---
- name: Set Banner
  hosts: csr:c9k
  gather_facts: False
  connection: local

  roles:
    - iosxe_banner

- name: Set NTP
  hosts: csr:c9k
  gather_facts: False
  connection: local

  roles:
    - iosxe_ntp

- name: Set Syslog
  hosts: csr:c9k
  gather_facts: False
  connection: local

  roles:
    - iosxe_logging

- name: Configure Vlans
  hosts: c9k
  gather_facts: False
  connection: local

  roles:
    - iosxe_vlans

- name: Configure Vrfs
  hosts: csr:c9k
  gather_facts: False
  connection: local

  roles:
    - iosxe_vrf

- name: Enable IOSXE Model Driven Programmability
  hosts: csr:c9k
  gather_facts: False
  connection: local

  roles:
    - iosxe_mdp
