--- 
- name: Generate Configuration from Template
  hosts: csr
  gather_facts: False
  connection: local

  tasks:
    - name: "Generate Config"
      template: 
        src: "../bgp_temp.j2"
        dest: "../config/{{hostname}}_bgp_config.conf"
